### ISSUE TITLE
ActionCreator returning multiple actions

### ISSUE THREAD

**Issue by wpK** [ReSwift/ReSwift#112]
Great job on ReSwift so far. Ever since Flux was released I was interested in a project such as this.

There are cases where an ActionCreator would be very useful. For example, looking at GitHubBrowserExample, the action [authenticateUser](https://github.com/ReSwift/GitHubBrowserExample/blob/master/SwiftFlowGitHubBrowser/Actions/AuthenticationActions.swift) dispatches two actions and then returns nil.

Redux has middleware (e.g. [redux-multi](https://github.com/ashaffer/redux-multi)) that allow returning multiple actions. Is this something the ReSwift community would be interested in? If so, should ReSwift support it directly or have a middleware project that does?

**Comment by Ben-G** [comment]
@wpK This sounds like a good idea, especially since you've already identified a valid use case. I think it would be interesting to try and put this into a middleware instead of the core. Having a small core makes it easier for teams to understand & adopt ReSwift.

This would also be a very interesting test case for porting a small Redux middleware to ReSwift. Due to our static type interface on `Middleware` we might need some changes to ReSwift to accomplish this.

Right now the `dispatch` function requires an `Action`, but we would likely need to use `Any` to make middleware more flexible: https://github.com/ReSwift/ReSwift/blob/master/ReSwift/CoreTypes/Middleware.swift#L11

Would be great if you would be interested in giving this a shot!

**Comment by wpK** [comment]
@Ben-G it would be great to add more flexibility to middleware as there are so much middleware already for Redux and a lot of it could easily be ported over.

The middleware mentioned would take such little effort to implement. When I have a bit more time I'll send you a pull request.

**Comment by DivineDominion** [comment]
Action creators were replaced with https://github.com/ReSwift/ReSwift-Thunk/
