### ISSUE TITLE
Side effects in newState?

### ISSUE THREAD

**Issue by AndrewSB** [ReSwift/ReSwift#136]
What is the best practice on performing side effects, like presenting a `UIAlertController` in newState? Is this alright?

```
    func newState(state: LoggedInState) {
        self.stopLoading()
        switch state {
        case .ErrorLoggingIn(let error):
            presentViewController(UIAlertController(okayableTitle: "Couldn't log in 😔", message: error.localizedDescription), animated: true, completion: .None)
        case .LoggedIn:
            print("Logged in")
        case .NotLoggedIn:
            print("still not logged in")
        case .Logout:
            assertionFailure("Cant logout from this screen")
        }
    }
```

**Comment by DivineDominion** [comment]
I assume this is in a presenter of `UIViewController` or something. So that looks totally fine! 

What made you wonder if you did this right? Maybe that'll help figure out a good next step :)

For example, since the "effects" vary from showing an alert to doing something after logging in, you could make an `Effect` enum from the state to separate the two like @mokacoding: http://www.slideshare.net/GiovanniLodi2/functional-core-reactive-shell/48

**Comment by AndrewSB** [comment]
The reason I was wondering was that the couldn't log in alert was being presented each time there was new state - sometimes popping up 4-5 times in a row due to async state being loaded in from the network.

Since, I've dispatched an action in the alert view's completion that sets the loggedInState to `.NotLoggedIn`, so you don't see repeated alerts.

Thanks @DivineDominion
