### ISSUE TITLE
[Fix Documentation] ReSwift crashes when dispatched repeatedly on a concurrent queue

### ISSUE THREAD

**Issue by langford** [ReSwift/ReSwift#185]
As this example project shows, ReSwift crashes with a "ReSwift:IllegalDispatchFromReducer - Reducers may not dispatch actions" error when you dispatch many Actions from a single concurrent queue. 

Make sure you hit the button rapidly to see this problem. I am seeing this in a non-toy project and have extracted this functionality to ensure it was ReSwift, and not another part of our code triggering this. 

https://github.com/langford/ReSwiftConcurrentQueueBug

If this is by design, expanding the particular error message and documentation around Concurrent GCD queues would help people a great deal, as they are exceedingly common when dealing with a lot of background activities in which state management makes sense. The current comment about "main queue recommended" does not say "but whatever you do, use a single serial queue". Until this bug is addressed, it likely should say that. 

I am happy to offer a doc patch to do that if this behavior is by design.

**Comment by agentk** [comment]
You are correct. The documentation is not very clear. The reducers are required to be executed in a single serial process because the output state of the currently running reducer is required for the next. I think the best solution depends a lot on the situation, you could use a dispatch on thread call, mutex wait, single serial queue or an action dispatch buffer.

**Comment by DivineDominion** [comment]
In lieu of a better fitting label, "needs implementation" equals "needs clarification in the docs" here :)

**Comment by Ben-G** [comment]
This has been fixed here #189!
