### ISSUE TITLE
[Question] How to properly implement UITableView row changes?

### ISSUE THREAD

**Issue by pRizz** [ReSwift/ReSwift#186]
If I have a state change which deletes certain sections and/or rows, how do I get the information to call 
`func deleteRows(at: [IndexPath], with: UITableViewRowAnimation) ` or
`func insertRows(at: [IndexPath], with: UITableViewRowAnimation)`
etc., with the proper indexPaths? Is it possible or do we have to resort to `reloadData()`?

**Comment by Hxucaa** [comment]
I believe the problem can be solved in 2 ways.
1. Calculate a diff between the previous array of data and the current one. Then the table view can animate the changes based on the calculated diff. Use this library https://github.com/jflinter/Dwifft to come up with the diff.
2. Store deletion and insertion of table cell as events. The state of the the table view can be derived from the events.

The difference between method 1 and 2 is that in 1 you store the state (array of table cell data) and disregard the events (how the state is mutated from previous state to current state. In method 2, you'd store the events instead of state and you can drive the state based on the events. Of course you can also store a snapshot of the derived state, so that you don't have to calculate the state from the beginning of the list events every time.

**Comment by pRizz** [comment]
That makes sense. Thanks for your response!
