### ISSUE TITLE
Best practice to unit test actions being called

### ISSUE THREAD

**Issue by ysyyork** [ReSwift/ReSwift#194]
E.g. I have a ViewController and function like this
```
func a() {
    store.dispatch(aaAction)
    store.dispatch(bbAction)
    store.dispatch(ccAction)
}
```
How can I test if this function dispatches these three actions? Should I mock the whole store object?

**Comment by DivineDominion** [comment]
Currently, I circumvent the store's reducing and do it like this:

```
let storeDouble = Store(...) // I recommend setting this up with a "NullReducer" that does nothing
func testDispatchingAction() {
    var didDispatch: [TheAction] = []
    storeDouble.dispatchFunction = { 
        didDispatch.append($0)
    }
    viewController.store = storeDouble
    
    viewController.a()

    XCTAssertEqual(didDispatch, [
        TheAction("first action"),
        TheAction("second action"),
        TheAction("third action")
    ])
}
```

Requires your actions to be `Equatable` (for the test target, at least).

This is obviously non-ideal, because the mocking relies on the store's internals a lot. We should eventually come up with a `TestStore` that exposes the same interface as the regular `Store` but doesn't require any reducer, middleware, or initial state. Your thoughts on this, @Qata @mjarvis etc.?

**Comment by mjarvis** [comment]
@DivineDominion I would be inclined to leave any `TestStore` implementation out of ReSwift itself. That seems like a framework user's responsibility to mock. In my opinion, the best method for mocking the store without the store's internals is for the user to implement `StoreType`. (Related to that, I'm all for splitting up `StoreType` into smaller protocols so that users don't have to mock the whole thing)

**Comment by DivineDominion** [comment]
I see where your `StoreType`-related protocol cleanup plot is heading ... :) That could work, yes, and sounds like a clean solution. We should make sure not to release a version where `dispatchFunction` is unavailable _and_ the protocols haven't been refactored.

**Comment by timojaask** [comment]
In my code, I'm trying to use `DispatchingStoreType` protocol wherever possible – it's all you need if the only store functionality used in a function is dispatching.
```swift
public protocol DispatchingStoreType {
    func dispatch(_ action: Action)
}
```

This makes it a lot easier to mock store in tests. Something along these lines:
```swift
class TestStore: DispatchingStoreType {
    var dispatchedActions: [Action] = []
    func dispatch(_ action: Action) {
        dispatchedActions.append(action)
    }
}
```

**Comment by DivineDominion** [comment]
Good point. Can we improve anything inside ReSwift (like @mjarvis suggestion for smaller protocols) to improve the situation?

-- If not, I'd like to close this issue and move this to a FAQ into the docs.

**Comment by timojaask** [comment]
@DivineDominion I agree that splitting into smaller protocols could make it easier to use. For example, one for the state, another one for the subscribe method.

**Comment by DivineDominion** [comment]
Ok, it seems there's not much else going on; if you want to drive any protocol refactoring, as always feel free to open a new issue for discussion or a PR with proposed changes!
