### ISSUE TITLE
ObjectiveC support

### ISSUE THREAD

**Issue by cliren** [ReSwift/ReSwift#208]
I haven't seen an example of ReSwift with ObjectiveC and Swift combination yet (please point me to one if there is one). Our team is actively exploring the option to use ReSwift in an existing project with ObjectiveC + Swift, is ReSwift supported for use with ObjectiveC?

**Comment by mjarvis** [comment]
@cliren The most common way to use ReSwift in objective-c is to add project-specific wrappers to ReSwift code that is `@objc` compatible. The wrappers would be written in swift, and encapsulate any swift-specific functionality, exposing it in objc-compatible terms.

Designing state in such a way to be Objc compatible requires a bit more effort, because ReSwift is meant to be used with immutable state, which is more work to do using class types compatible with objective c.

**Comment by cliren** [comment]
Yes, its definitely more work and have to rely on non-value types. We will see how it goes but appreciate if anyone has other ideas or any example projects. Thanks @mjarvis for your inputs!

**Comment by DivineDominion** [comment]
I don't think there'll be a general solution. Sounds like a very app-specific problem -- since there was no ReSwift for ObjC people could have used, the whole data flow is likely not unidirectional at first. So you end up with 2 problems: redesigning the data flow and using ReSwift as backbone to deliver events.

To me it sounds like a good idea to tackle both problems with a custom ObjC-based unidirectional flow/event dispatching mechanism. Doesn't have to do much at first to keep the architecture changes local. You will need:

1. an object called `store` that can dispatch events (or `action`s)
2. use `NSDictionary` for the actions -- [like JavaScript Redux does](http://redux.js.org)
3. probably use `NSDictionary` for the `appState`, too, because deeply nested types aren't fun in ObjC
4. write reducers; they can be simple C functions taking in `(appState: NSDictionary, action: NSDictionary)` and returning `NSDictionary` again as updated state. Since your store is self-made, you can just hard-code a call to the `mainReducer` function in and delegate from there.
5. you won't need middlewares ✓ 
6. but you probably need tests to verify your stuff works ;(

Later, you'd be able to deserialize ReSwift events from dictionaries and pass them to the Swift store. And/or you serialize the state itself and pass it to ObjC subscribers. 

If you start with a simple ObjC unidirectional flow mini-"library" that works with dictionaries, you'll be able to write a common `ObjC_StoreSubscriber` as a wrapper around your ObjC objects in Swift. Instances of this type obtain state changes from ReSwift, make a dictionary from them, then pass them to the wrapped ObjC object.

**Comment by alexlee002** [comment]
@DivineDominion Why you said "you won't need middlewares ✓" ?  I'm not quite agree.  How do you deal with the async-actions?

**Comment by DivineDominion** [comment]
You can use action creation blocks, middlewares, or multiple sync actions (RequestStarted, RequestCompleted). I often avoid middlewares because it's hard to keep in mind when a Middleware will interfere with the flow -- and they can alter it too easily and make the data flow worse.

**Comment by DivineDominion** [comment]
@cliren how's it going? I doubt there'll be someone among the contributors willing to write an ObjC port right now -- so did you make progress with a self-made adapter?

**Comment by DivineDominion** [comment]
Closing this for now.
