### ISSUE TITLE
Question on where to put helper object

### ISSUE THREAD

**Issue by sarunw** [ReSwift/ReSwift#273]
I just start learning redux and have a hard time figure out where to put helper object. Everything in redux seem to be just function and struct, the closest example I can find is network call.

In the example of Action creator it use helper object named `Octokit`, this is where I should put create helper object?

If creation of helper object is very expensive i.e. Octokit(configuration) take second to create and I need to use `fetchGitHubRepositories` very often. Should I create Octokit elsewhere, but where should it be? The only place this global func can access is global var, but is that a right way to do it?

```
func fetchGitHubRepositories(state: State, store: Store<State>) -> Action? {
    guard case let .LoggedIn(configuration) = state.authenticationState.loggedInState  else { return nil }

    Octokit(configuration).repositories { response in
        dispatch_async(dispatch_get_main_queue()) {
            store.dispatch(SetRepostories(repositories: response))
        }
    }

    return nil
}
```

**Comment by DivineDominion** [comment]
Good point: the docs and example assumes you will just figure out what to do when your app is more complex :) But that doesn't help with grasping the concepts.

## Layered Approach 

Your `Octokit` type and the object you create with a `configuration` are not part of the ReSwift state ecosystem. I like to think in layers, because that's a very simple abstraction:

![screen shot 2017-07-23 at 12 46 51](https://user-images.githubusercontent.com/59080/28498747-39913354-6fa5-11e7-999b-13946a7d44e6.png)

So you have the UIKit stuff at the top (I like it at the top because the user looks at it and that somehow feels natural to me). Then there's the state stuff at the very core or bottom. And I drew a 3rd layer in between, by convention called "Application Layer", borrowed from _Domain Driven Design_. I like to think it's called "Application Layer" because it's the glue that makes your app what it is. For example, our state and even some UI components may be shared among targets, but the Application Layer stuff is the code you're going to write anew for every target platform. That's leaving out a lot of details, but it's a good start.

What you call "helper", I'd call Service Object. And it lives in the Application Layer:

![screen shot 2017-07-23 at 12 48 15](https://user-images.githubusercontent.com/59080/28498766-8f816478-6fa5-11e7-85d8-2ba912cf5312.png)

Like:

```swift
// typealias DefaultStore = Store<AppState>
class RepositoryFetcher {
    let octokit: Octokit
    let store: DefaultStore

    init(
        octokit: Octokit,
        store: DefaultStore
    ) {
        self.octokit = octokit
        self.store = store
    }

    func fetchAllRepositories() {
        self.octokit.repositories { response in
            DispatchQueue.main.async {
                self.store.dispatch(SetRepostories(repositories: response))
            }
        }
    }
}
```

You see, this service is only responsible for fetching stuff. It does not check if the user is logged in, and it is not a `ReSwift.StoreSubscriber` itself. I picked this design because this is closest to the notion of a "helper" object. Which means you'll need to perform the checks elsewhere. Or you can cram it into this type, too, by checking for `store.state.authenticationState`. This is not just "fetching", it's a different activity (or responsibility), so that's why I'd leave it out.

This approach scales pretty well for lots of different helper objects. You may need to figure out where you want to store the instances, though. In the AppDelegate? A global variable?

## Simple stateful functions

As you said, you can make the `Octokit` instance global. That will work and it might not even cause trouble in your app.

You can also make it part of a nested closure, maybe like this:

```
public fileprivate(set) var fetchGitHubRepositories: ()  -> Action? = { 
    preconditionFailure("Call setupFetchingHelper(octokit:) first")
}

public func setupFetchingHelper(octokit: Octokit, store: Store<State>) {
    fetchGitHubRepositories = {
        guard case let .LoggedIn(configuration) = store.state.authenticationState.loggedInState  else { return nil }

        octokit(configuration).repositories { response in
            DispatchQueue.main.async {
                store.dispatch(SetRepostories(repositories: response))
            }
    }
}
```

This is not tested, but something like it should work. Instead of a global variable, you end up with a function (a block, really) that you can reconfigure if you need to create a new `Octokit` instance. It's still just a global variable, really, but you see that the call gets simpler and that you can make sure that the Octokit requests are performed on the same background queue, for example.
