### ISSUE TITLE
Best practice to execute a chain of dependent actions

### ISSUE THREAD

**Issue by the4thfloor** [ReSwift/ReSwift#277]
Hi,

what is the best way to execute a chain of dependent actions? In my case the user scans a QR code. If the code is scanned I call a backend to login the user. If the login is successful I have to load the user profile.

So I have a action to trigger the login process:
```
/// start whole registration process
struct login: Action {
    let extraUsername: String?
    let qrData: GSPQrData
}
```

And I created a middleware wo start the dependent actions:
```
let loginMiddleware: Middleware<AppState> = { dispatch, getState in

    let log = XCGLogger.default
    let app = AppDelegate.shared

    return { next in
        return { action in

            let callManager = app.callManager
            switch action {

            case let login as login:

                // store state
                next(action)

                if !(callManager?.initializePortSip(sipServIP: login.qrData.sipServIP!,
                                                    sipServPort: login.qrData.sipServPort!,
                                                    sipUser: login.qrData.sipUser!,
                                                    sipPass: login.qrData.sipPass!,
                                                    userName: login.extraUsername) ?? false) {
                    return next(logout())
                } else {
                    return
                }

            default:
                break
            }

            return next(action)
        }
    }
}
```

It works so far but I'm not sure if it is a good way to do that. Especially the `next(action)` (at the beginning of the login case) to store the QR data in my AppState looks weird.

Another try was to have a manager class which registers for state changes:
```
    self.store.subscribe(self) { (subscription: Subscription<AppState>) in
        subscription
            .select { (state: AppState) in
                state.loginState
            }
            .skipRepeats { ( oldState: LoginState, newState: LoginState) in
                oldState.connectionState == newState.connectionState
            }
    }


    func newState(state: LoginState) {

        // handle login related states
        switch state.connectionState {
        case .qrCodeScanned:

            if let qrData = state.qrData {

                if !initializePortSip(sipServIP: qrData.sipServIP!,
                                      sipServPort: qrData.sipServPort!,
                                      sipUser: qrData.sipUser!,
                                      sipPass: qrData.sipPass!,
                                      userName: state.extraUsername) {
                    self.store.dispatch(logout())
                }
            } else {
                self.store.dispatch(logout())
            }

/// ...
```

This works too but now I moved the action work to another class and I have to have a `qrCodeScanned` state which only exists to trigger the next step.

I guess the best thing would be a middleware like thing which runs after the reducer changed the AppState.

**Comment by DivineDominion** [comment]
I don't know about a _Best Way™_, but am curious what others might point out here. I favor the second approach (with the subscription being done by another object than the subscriber itself) of very focused service objects that perform requests and dispatch follow-up actions. 

Side note: I use Middleware for manipulation of actions or state. And I use them for side-effects that are contained within my state module, mostly dispatching another action. They do not perform app-related logic. And they have no clue about any infrastructure, including the Internet. 

But you are right, the state object becomes a lot more complex because you have to enqueue or buffer requests until they are handled in a state variable. When you're exploring setting up the state and ReSwift, that's a downside compared to Redux, where you do not need to define properties on the state object -- but of course traded in for the usual upsides of strong Swift types. But the ceremony is not much work, albeit repetitive: writing a state property, writing a reducer, wiring the reducer from the main reducer, creating the actions.

**Comment by timojaask** [comment]
> I guess the best thing would be a middleware like thing which runs after the reducer changed the AppState.

That would be a store enhancer, like in Redux, which unfortunately not yet implemented in ReSwift. Related issue: https://github.com/ReSwift/ReSwift/issues/1
