### ISSUE TITLE
State normalization

### ISSUE THREAD

**Issue by khrykin** [ReSwift/ReSwift#285]
Hi! Coming from redux I'm really having lots of fun with ReSwift, but I just can't decide what's the best choice for handling reational data in case of swift.

In js world, in redux we mess with [normalizr](https://github.com/paularmstrong/normalizr) and [selectors](https://github.com/reactjs/reselect) in order to benefit from normalized state and keep relational data consistent, I assume same pattern applies for ReSwift?  

With `struct`s being value types it would require some manual work to keep nested structures consistent, `class`es on the other hand, don't have all advantages of immutability, but being reference types, they don't need to be synchronized... 

So what would be the best approach here?

**Comment by DivineDominion** [comment]
I am familiar with neither. Can you explain what you want to achieve?

**Comment by danielmartinprieto** [comment]
Hi, @khrykin!

Yes, both normalized state and memoized selectors are still good practices while using ReSwift, as it's based on the same concepts as Redux.

It doesn't matter if they're value types or not in order to maintain immutability. In fact, in JavaScript you only have reference types and you can "enforce" immutability by convention (Redux docs will tell you this all the time). Also, if you declare a variable of a reference type in Swift with let, and all its properties are let as well, you get the same immutability. It's when you copy the instance when things get messy, and the way Redux in JavaScript handles this (without using a third party lib or `Object.freeze`) is, as I said, by convention: just returning a new instance each time from your reducers. Redux uses reference equitability to skip updates by default, and ReSwift uses the Equatable protocol, which works the same way for structs and classes.

I don't know a generic library like normalizr for Swift, if you find one, please let me know! What I do instead is a) convince my API colleagues to send me the data already normalized (which is anyway a good practice), or b) when I'm parsing the JSON, I normalize it myself, which is a bit tedious but it's ok if the shape of the data you're dealing with is not super complex. Normalizing the shape of your state in Redux/ReSwift has indeed a huge impact later writing your reducers and quering the store.

Regarding selectors, it's also a great practice to memoize them, and I'm pretty sure there are already open source libs doing this so you can use one of them to write your selectors. I'd only do this if you have a fairly complex logic to query your data once an update has been triggered by ReSwift, though.

**Comment by khrykin** [comment]
@DivineDominion For e.g. just something simple as `User` - `Post` `1:n` relationship. 

With normalized state if I update user, I don't need to query all posts for that user and update them too. In the UI, however I need to query user like `let user = usersState.users[comment.userId]` for every post (e.g. in `UITableViewDataSource`'s `tableView:cellForRowAt:indexPath` method).  So `usersState.users` must be something like dictionary or array, and `userId` some unique `Int` or `String` or whatever.

If your data relationship is not so simple it would be reasonable to use memoized function that "selects" i.e. derives your data from state in order to run computation only when dependent data changes.

@danielmartinprieto, thanks for the reply!
So is this state shape ok (something I would do in js), or there are some better ways in swift?

```swift
struct Post: State, Equatable {
    var content: String
    var userId: Int

    static func ==(lhs: Post, rhs: Post) -> Bool {
        return
            lhs.content == rhs.content &&
            lhs.userId == rhs.userId
    }
}

struct User: State, Equatable {
    var name: String

    static func ==(lhs: User, rhs: User) -> Bool {
        return lhs.name == rhs.name
    }
}

struct UsersState: State {
    var users = [
        1: User(name: "Raphael"),
        2: User(name: "Michelangelo")
    ]
}

struct PostsState: State {
    var posts = [
        Post(content: "Hello", userId: 1),
        Post(content: "Hello", userId: 2)
    ]
}

// Somewhere in UI

let usersState = UsersState()
let postsState = PostsState()

// for post in postsState.posts

let content = post.content

let user = usersState.users[post.userId]
```

**Comment by danielmartinprieto** [comment]
Yeah, I’d go even further and store the posts in a dictionary as well, and keep the id for all objects (actually, if you’re sure two users can’t have the same id, your Equatable conformation can be simplified a lot in a more lightweight manner).

Also, in my experience, I usually need to store an array of ids of some entities, so in my UI I can have and respect a certain order. Sometimes one can think that it’s doing the job twice, but this separation pays off.

**Comment by khrykin** [comment]
@danielmartinprieto Sure, I just wanted to show the simplest example possible. Could you please explain more how to simplify `==()` ?

**Comment by danielmartinprieto** [comment]
Yes. If you have a user like this:
```
struct User {
    let id: String
    let name: String
}
```
coming from the API and you know that the id is unique within your system, you can conform to Equatable just doing `lhs.id == rhs.id`.

**Comment by khrykin** [comment]
@danielmartinprieto Oh, I got it)) I thought there was some magical swift thing xD

**Comment by danielmartinprieto** [comment]
Yeah, nothing fancy about it, sorry, hehe.

**Comment by DivineDominion** [comment]
This is interesting. I now understand why I didn't understand the problem earlier :) The ID:User dictionary @danielmartinprieto proposed sounds like a local repository. That's not part of my app states. But I don't do web service based apps anyway at the moment, so my thinking might be biased. At the moment, I'd put the structured content in the app state -- and, if really needed after that, maintain caches as object repositories (with or without locally persisted databases) outside the state. Just like a SQLite database is not part of the app state, but the app's context, accessible via its infrastructure.

**Comment by khrykin** [comment]
@DivineDominion I believe the problem isn't specific to web service-based apps. The main question here is how you manage updates when object that needs to be updated can be found in different levels of a state tree? 
If state is normalized and you reference that object by some `id` you need to perform an update in only one reducer, but if it's not — in every dependent reducers, which isn't very scalable and actually error-prone. However, retrieving from store an actual data that needs to be displayed may get pretty complex, hence selectors.

**Comment by danielmartinprieto** [comment]
The state of your app should be a cache of you're retrieved data coming from other sources (local database, server, user input) plus some info to keep your UI under control. As @khrykin said, it's not only about web services, and having more than one source of truth locally is considered an anti pattern (simply because then you need to sync not only the client data with the remote/database one, but also with all the other entities in the client).

Normalising your state shape gives you more granular control about how to read and update it, which means that you'll have less complex reducers to deal with. You write selectors to _put back_ some info together before pass it to the UI (the way the UI needs it, not the way it came from the source), and to be able to memoize them later (just another place where you can do some performance optimisation in case you need it). This helps you derive the information you already have without having to store duplicates, therefore enforcing the single source of truth paradigm.

**Comment by DivineDominion** [comment]
Now it gets interesting :)

> The state of your app should be a cache of you're retrieved data coming from other sources (local database, server, user input) plus some info to keep your UI under control. 

Do you have any argument _for_ this claim? I said kind of the opposite so far, but earlier :) I still think I'm right because a cache may include all objects that were retrieved during the session for faster display, whereas the state has to contain 100% of the data needed to populate the view. A cache and the state may overlap. But a cache may have many more entities than the state contains; and the state may contain additional view configurations that are not part of the cache.

> This helps you derive the information you already have without having to store duplicates, therefore enforcing the single source of truth paradigm.

That's interesting, because this is like second-order singleness of the source of truth. Let's say I display a timeline with a photo and a detail view with the photo on top in a modal window. The state will have a reference to the image in the timeline list and in the modal window content substate. You seem to suggest that there should be only one source inside the state, the "normalized state cache", and that both timeline and modal window should reference the entity from the cache by ID. Did I get that right?

**Comment by danielmartinprieto** [comment]
Yes, that's it! You shouldn't be duplicating the entity (the one with the photo, let's say the `User` with id `"42"`) stored in your state just because you want to show it in two different places in your UI.

I don't like to call it "cache", because it's not as simple as that, but yeah, it's kind of a cache plus something else. That "something else" it's what you need on top of your data to populate your view, but only the things that can't be derived from the info you already have, to avoid duplications.

The arguments are:

- You actually don't need that duplication at all. It doesn't make sense that you have two instances of the user 42 saved in your state, you can save it once, and then use the id as a reference to store other things -user input as a collapse/open section, draft data from a form related with the user...-, and to get info about that original user.
- If you duplicate it, you have to maintain the copies later, which is more work and error prone. Imagine that you start following the user 42 and now, when the operation succeeds -either locally or remotely-, you have to reflects this operation twice in your state because you have several copies of that entity.

**Comment by khrykin** [comment]
> state has to contain 100% of the data needed to populate the view

@DivineDominion I'd say that state has to contain _minimum_ amount of data  needed to populate the view. I.e. don't store in state anything that can be _derived_ from it. This really thins out your reducers. No need to maintain cache vs state consistency, because in this case the state is kind of "cache" itself, holding only data that needs to be displayed in current view or in any views that could show up next.

Btw, if you need to have a certain editable order in your list, as @danielmartinprieto mentioned earlier, you achieve that by maintaining an array of `id` s next to your `[id: T]` dictionary, something like

```swift
struct PhotosState {
  typealias Id = Int
  var items: [Id: Photo]
  var order: [Id]

  func photo(at index: Int) -> Photo? {
    guard let id = order[index] else { return nil }
    return items[id]
  }
}
```
Further you can make this state shape even fancier: e.g. add mutating methods, conform it to `Sequence`, etc. 

 I found it plays even nicer in swift than in js.

**Comment by DivineDominion** [comment]
I use something similar, only that it's a "Repository" class and manages all locally available data. (Which, in my case, is everything; the only changes I need to sync with are file system changes, but the Repository is the only database-like thing there is.) 

It's interesting that you put it into the state. I still don't see a benefit. :)

> You actually don't need that duplication at all. It doesn't make sense that you have two instances of the user 42 saved in your state, you can save it once, and then use the id as a reference to store other things [...]

Swift structs are copy-on-write, so if I have a `Photo` object in my repository and then put it into 2 places in the state (let's call it `PhotoDetailState` for the modal window and `TimelineState` for the timeline), the data isn't really duplicated. There are 3 references, of course. Referencing the ID value objects in 2 places does not reduce the overhead.

But at least then you _know_ it's only an ID and not the data itself, so you know you have to fetch the details as needed. Which is a nice segue:

> If you duplicate it, you have to maintain the copies later, which is more work and error prone. Imagine that you start following the user 42 and now, when the operation succeeds -either locally or remotely-, you have to reflects this operation twice in your state because you have several copies of that entity.

I'd like to know: How do you trigger view updates? 

In a naive approach based on my not-inside-the-state-Repository, in the worst case I'd look at all possible substates if the `PhotoId` is used and replace the `Photo` instance. It seems you have to do a similar thing, or maybe even fetch the `Photo` anew every time the user taps "Back", because all you have in the ID and you (have to?) assume that the view data is outdated.

> don't store in state anything that can be derived from it

Right, that's the concern of assembling the data structure to be consumed by the view, e.g. the view model.

**Comment by Elshad** [comment]
Hi @danielmartinprieto 
How you, for example, fetch needed for UI list of posts from normalized list posts. In app state may be 100 normalized post, but i need 10 post to show in UITableView.

**Comment by danielmartinprieto** [comment]
Hi, buddy. 

Do you mean once they’re in your ReSwift state? I would create a selector with the type signature `State -> [Post]` and call it in your view controller inside the subscription (`newState` function).

That selector is just a pure function that knows how to extract the relevant 10 posts from your normalized state.

Hope this helps.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Elshad** [comment]
@danielmartinprieto 
Yes, once they’re in my ReSwift state.
I attached example image. Do i need send followers id list as parameter to selector to fetch list from normalized list or there is more accurate way for this?
![img_6571](https://user-images.githubusercontent.com/2334731/53793270-ef814d80-3f46-11e9-9c5d-ee97d6d790b8.jpg)

**Comment by DivineDominion** [comment]
Sounds like you'd want something that takes the normalized list, applies a filter, then sets the state accordingly. It looks like the normalized state is like "all data", and the follower's list is like "UI selection". I usually dispatch an action that sets the UI data as a new substate (read `state.allUsers`, filter, then set `state.followers` to the result for example). You can then subscribe to this substate directly.
