### ISSUE TITLE
Issue Management

### ISSUE THREAD

**Issue by candostdagdeviren** [ReSwift/ReSwift#292]
I would like to contribute more to ReSwift. I've been watching this library ~2-3 months and I lost myself in the issues in general. Except for 'Needs Discussion' and 'Question', other issues are mostly non-tagged and has no state. So, I was thinking where to start in the beginning?

Here is a start for me. My suggestion is using proper tags for issues. If issue should be implemented, we can use some level tags like 'starter-task', 'moderate-task', 'advanced-task'. If it won't be implemented but we want to keep in mind the proposal, we can say 'no implementation-idea' (or whatever, naming is hard). This style can increase contribution to the library and give people a start point depending on their experience with ReSwift. There can be other styles or more improvement on this. So what do you think, people of ReSwift?

**Comment by DivineDominion** [comment]
I like improving the focus for contributors using a different set of labels in addition to the existing set. 

Thinking about the problem difficulty tiers, "moderate" and "advanced" seem hard to grasp. (CocoaPods uses easy/moderate/hard, I think.) I wonder if it would suffice if we just had `difficulty-beginners` and "advanced". Because most non-trivial tasks are basically proposals we discuss and not open tasks to implement.

**Comment by candostdagdeviren** [comment]
About difficulty layers, your suggestion sounds good to me.

One more thing, new "documentation" label can be used for only documentation update requests/tasks/etc.

**Comment by DivineDominion** [comment]
Closing this for now as we have some GitHub supported labels now.
