### ISSUE TITLE
State Serialization

### ISSUE THREAD

**Issue by Ben-G** [ReSwift/ReSwift#3]
Currently only actions can be serialized, but not the application state. This means time traveling and state restoration are only possible by replaying a sequence of actions, not by setting the application to an arbitrary state.

We should evaluate how much benefits a serializable state would bring (for me crash reporting comes to mind) and figure out if there's a convenient way for developers to implement state serialization or if we can generate the required code.

**Comment by DivineDominion** [comment]
Since actions are essentially events, the same convenience mechanisms of event stores come to mind. There, the current state is replayed through all events of the system. Next to that, every _N_ > 50 events the store can create a snapshot of the resulting state to optimize replay. Instead of starting with a blank state and performing all changes, you start with a state snapshot and replay only the events that came after.

I always found Cocoa lacks a cool event store library. So we'd have to improvise on this. App state and its sub-states has to be serializable, either as JSON or NSData, to do what an event store as SQL or NoSQL database does.

**Comment by DivineDominion** [comment]
@mjarvis @dani-mp I closed this because I believe users can patch this functionality in with a `RestoreAppState` action that is handled by the root reducer. If you think this should be a stretch goal for e.g. v7, please reopen
