### ISSUE TITLE
Question about accessing state inside the app

### ISSUE THREAD

**Issue by ranhsd** [ReSwift/ReSwift#309]
Hi, I decided to use ReSwift and ReSwift-Router for one big project that i'm developing and so far i am very happy that i am using this library because soon as you understand it (and it takes some time :) ) you see how powerful it is and how simple and easy it is to add more features and to understand the app flow. 

I have a very simple question regarding accessing the state. I know that in order to **change** the state you must implement a reducer and that's what i'm doing... But in part of the apps i need to access the global store in order to do something. I will provide an example: 

In my AppState i have a sub state which called **authenticationState** one of its properties is the logged in user. In my app i need to access this user (read only) in order to send it's id to the network request so what i'm doing is the following: 

`query?.whereKey("user", equalTo: store.state.authenticationState.currentUser!)`

I'm not accessing it in the authenticationReducer but inside a view controller or AsyncAction. Again this is **read only**. I wanted to ask if this is allowed or not?

Thanks in advance!

**Comment by mbroski** [comment]
Experience has taught me that it is always better to subscribe rather than dig into the app state to read the current value.  So why not just subscribe to `store.state.authenticationState.currentUser`?

**Comment by DivineDominion** [comment]
Accessing the state like you do is no problem, in principle. ReSwift makes sure you do not dispatch actions from multiple queues at the same time, though dispatching on the ma8n queue is not required. If you read the value from the main queue and don’t do anything fancy with concurrent wueues, this read operation is safe.

When you write an app with ReSwift in mind, try to architect the data flow as “push” or “east-oriented”, favoring subscriptions and delegation over value queries.

- Do you display the user name? Make sure you subscribe to the state and assemble what might be called a view model to make updating the view easy.
- Do you need the user credentials for network requests? Consider subscribing a network request service to the current user credentials (this updates `NetworkRequestHandler.currentUser` to cache the state and prevent unauthorized requests); but I’m not an expert when it comes to network requests because none of my apps performs any :) So better listen to other people’s advice when it comes

**Comment by ranhsd** [comment]
Hi @DivineDominion thanks for your reply. In all the examples i saw that the states and sub states that are defined are with **var** and i think it's better to use **let** instead in order to not allow change the state outside the reducer. I like to view model approach and i am planning to use it soon but i think it's better to do it with binding library (e.g. RxSwift) otherwise, MVVM concept is not so helpful. In some examples i also noticed that if for example you have array of items in your state there is another copy of it in your view controller and i don't know if it's really needed because i can just access my state directly ... what do you think about it?

About network requests what i did is create AsyncActions which receive the relevant parameters that i need, execute the network request and in the callback i dispatch the relevant actions in order to update the relevant states in my app. In order to make it look better i extremely recommend to use [PromiseKit](https://github.com/mxcl/PromiseKit) which really makes your code look nice and clean and saves you from whats called **callback hell** . Anyway, i looked on several ReSwift examples and all of them are using different approach for example in your ToDo app i saw that you use ReSwift a bit different than how i am using it but of course the flow must be the same (store, action, reducer and states) ...

**Comment by DivineDominion** [comment]
You can use let instead of var if you prefer to create new state instances from the root on up, sure. Being able to modify the properties is not problematic when you use value objects, which I recommend.

AsyncActionCreator is supposed to provide a state accessor, so that’s no problem 👍

When I said “view model”, I mean simple data transfer objects that expose a simple set of properties with strings and images that may be assembles from a complex object graph, to hide the object graph’s details from the view.

**Comment by ranhsd** [comment]
Hi @DivineDominion yes.. but currently i must use some SDK in order to save time for a new project that i'm working on and they kind of "force" you to create classes for the data models. I personally prefer to create structs in order to be immutable. I need to find a time to work on some abstraction layer on top of it that will return only struct based models...

I know that if i use let i must create the initial state to all of the state in my store at the beginning .. do you think that it's ok or not?

**Comment by DivineDominion** [comment]
Uh-oh, sounds like a situation similar to making Core Data NSManagedObject subclasses part of your ReSwift state. I wouldn’t do that and keep the state core pure, with immutable value objects and pure functions as reducers. The external dependency goes into the infrastructure concerns of the app, not the state. Everything else will bite you in the end, I prophesize :)

**Comment by ranhsd** [comment]
Hi @DivineDominion i totally agree with you. Currently i don't have a choice because i don't have a lot of time to change it but i will do it later. If you want to use **by reference** objects you need to take in account that you will need to manage it on your own and make sure its consistent

**Comment by DivineDominion** [comment]
Ok, then I’m closing this as the original question was answered. Reopen if you need anything else on this topic!
