### ISSUE TITLE
Share state between reducers

### ISSUE THREAD

**Issue by ranhsd** [ReSwift/ReSwift#364]
Hi, I have some question about accessing state inside a Reducer. 

In my app I have multiple sub states. It's actually sub state for each view controller. Now for each sub-state I have a reducer that change it. For simplicity let's assume that I have the following AppState

```
struct AppState {
   let currentUserState : CurrentUserState
   let itemState : ItemState
}
func appReducer(action: Action, state: AppState?) -> AppState {
    return AppState(
       currentUserState: currentUserReducer(state: state?.currentUserState, action: action),
       itemState : itemReducer(action, state: state?.itemState, action: action)   
   )
}
```

My question is: what should I do if I need to access the **currentUserState** or part of it inside the itemReducer.  I need it because the itemReducer must know if the current user is logged in or not and react to it. The user loginInfo is stored inside the **currentUserState** and as much as I know it's not recommended to do: store.state.currentUserState inside the itemReducer function. I wanted to know what is the recommended way to do it. 

Thanks in advance.

**Comment by mbroski** [comment]
I’d say two things on this.

1) I’ve found it helpful to keeping real business logic out of reducers.   Better to have some sort of component— what I call a `Feature` class-- that pays attention to global changes like authentication.  This class determines what actions are best at the appropriate time.

2) This could be an opportunity for middleware.  Middleware would intercept your actions before they get to the reducers.  A middleware class could check authentication state, then swallow or redirect the action as needed.


Mark

Mark Broski | Senior Manager
mbroski@captechconsulting.com
c 804.647.0920 / o 804.355.0511

[X]<http://www.captechconsulting.com/>

[X]<http://www.facebook.com/CapTechCareers> [X] <http://www.twitter.com/CapTechListens>  [X] <http://www.linkedin.com/company/captech-ventures>  [X] <http://www.stackoverflow.com/jobs/companies/captech-consulting>  [X] <http://www.youtube.com/user/CapTechConsulting>  [X] <https://www.instagram.com/lifeatcaptech/>
Best Firms 2016 #2 in Information Technology



On July 19, 2018 at 8:36:38 AM, Ran Hassid (notifications@github.com<mailto:notifications@github.com>) wrote:

Hi, I have some question about accessing state inside a Reducer.

In my app I have multiple sub states. It's actually sub state for each view controller. Now for each sub-state I have a reducer that change it. For simplicity let's assume that I have the following AppState

struct AppState {
   let currentUserState : CurrentUserState
   let itemState : ItemState
}
func appReducer(action: Action, state: AppState?) -> AppState {
    return AppState(
       currentUserState: currentUserReducer(state: state?.currentUserState, action: action),
       itemState : itemReducer(action, state: state?.itemState, action: action)
   )
}


My question is: what should I do if I need to access the currentUserState or part of it inside the itemReducer. I need it because the itemReducer must know if the current user is logged in or not and react to it. The user loginInfo is stored inside the currentUserState and as much as I know it's not recommended to do: store.state.currentUserState inside the itemReducer function. I wanted to know what is the recommended way to do it.

Thanks in advance.

**Comment by danielmartinprieto** [comment]
@ranhsd In my experience, when something like this is happening is because I'm coupling logic that shouldn't belong together. Ideally, you would react in your views to some changes in different parts of your state and make decisions there. Also, some actions won't happen in certain circumstances because they won't make sense (for instance, if the user isn't logged in, you won't be able to dispatch a change on their avatar because that part of the UI won't be loaded), and finally, you know that all reducers manage certain parts of the state, but they can be recalculated based on **all** actions (for instance, if you dispatch a log out action, you can reset different reducers at once, not only the ones related with the user's authentication).

I hope this makes sense to you!

**Comment by ranhsd** [comment]
@danielmartinprieto thanks for your answer but it's really depend on the app that you're building. For example in my app I need to show to **guests** users also some part of the Item but I need to check if they were logged in or not.

**Comment by DivineDominion** [comment]
I usually partition my reducers _by action_ instead of _by substate_. Those that need access to multiple substates or the root state are passed `AppState`; those that only need substate info are passed e.g. `ItemState`. That should help.

Also, maybe the underlying question is not about how to access other substates, but how to utilize login info that is needed in various parts of your app. To that question, there are different answers, so maybe ask that if that's what you're really puzzled with.

**Comment by ranhsd** [comment]
Hi @DivineDominion I am talking more about REDUX selectors (If you are familiar with...) selectors allows you to **derive state** to other sub states in your app. Of course that I can add another property in my ItemState of logInStatus or something similar and set it with an action but the idea of selectors is to keep the store as small as possible and as simple as possible to avoid complexity and to reuse state properties in multiple places.

**Comment by danielmartinprieto** [comment]
@ranhsd what you're looking for is in this sentence I wrote before: _Ideally, you would react in your views to some changes in different parts of your state and make decisions there._

**Comment by DivineDominion** [comment]
@ranhsd The virtue to keep the state as small as possible sure sounds nice an all, but you don't tell what you want to do :)

Maybe this is a case of the http://xyproblem.info/? :)

What do you need the auth info for? @mbroski  suggested middleware -- you could swallow actions (e.g. not process them) before they reach reducers in a middleware: `if state.isLoggedIn { next(action) }`, otherwise do not forward, for example. If you need to access the `userName` when you reduce `FooAction`, well, then write reducers differently, I suggest. _Or_ you need to stop dispatching certain kinds of actions when the `state.isLoggedIn == false` in the view controller or whatever is dispatching them, as @danielmartinprieto suggested. 

You need to be more specific about the problem you want to solve, not just the effect you fail to achieve, I suggest.

**Comment by ranhsd** [comment]
Hi @DivineDominion the auth is only one example. There are so many examples. I will try to explain it more. 

In my app each view controller subscribe to one sub state. I have a lot of view controller in my app that each one of them subscribe to specific sub state all the sub-states together construct on big Redux AppState. I also divided it into Actions so each one of the view controller has its own actions which are being dispatched from time to time during the specific view controller lifetime (e.g. network requests, update the UI and so on). Now each one of the sub-states has its own reducer. The reducer listen to actions which are being dispatched in the view controller but it also listen to actions from other view controller. So if for example I updated the user first name in the profile screen other screens which also use the user first name can update their UI as well. 
Now sometimes in my reducer I need to access to values of other states in my REDUX store but in my current architecture each one of my reducer receive the **sub-state**  as an input and need to return a new one and this specific sub-state sometimes not contains some data that I need. my example on the loginStatus is just one but there are more examples like: user info, settings info and more. I read about how REACT/REDUX solve this issue and they do it by deriving the state and this is done via selectors. There is a very popular library in here: https://github.com/reduxjs/reselect which solve it

**Comment by ninjaprox** [comment]
@raheelahmad: As you mentioned selectors, ReSwift also has this feature actually. It (and the library you mentioned) doesn't seem to solve the issue, since selectors are meant for use from store to views. Of course, you can use selectors to create a composed state from substates, and pass to reducers. This leads to the question: what does prevent you from simply doing that without need of selectors? e.g. ```itemReducer(action, state: (state?.itemState, state?. currentUserState), action: action)```

Even so, it raises another question: What if it doesn't only happen for one reducer or one substate (which I guess your case)? For example, there're 4 substates A, B, C, and D. To reduce A, the reducer needs A and B; to reduce B, the reducer need C and D, and so on. If it's really the case, @DivineDominion's [suggestion](https://github.com/ReSwift/ReSwift/issues/364#issuecomment-406291379)(and others') should help.

I will also consider reorganize the store to avoid this couple between substates. One substate for each view controller might not a good idea as it implies you're using the store to keep view states as well (not completely wrong though), while it should keep data, and data are displayed to views (through selectors if necessary), as @danielmartinprieto's [comment](https://github.com/ReSwift/ReSwift/issues/364#issuecomment-406315758).

**Comment by danielmartinprieto** [comment]
Yes! Selectors are already built in ReSwift, check this [example](https://github.com/ReSwift/ReSwift/blob/f2f0304cf1623100cee0beabae42948d5c6f138e/Docs/Getting%20Started%20Guide.md#example-with-filtered-subscriptions). Using that function you can map the whole state of your app to a substate with only the pieces of information that you need.

As I understand it, the whole point or Redux and its (sometimes hated) boilerplate is the separation of concerns. That's why it's not (a priori) a good idea to couple state, actions and views.
- Organise your state as a normalised database, without duplicating information and without heavy nesting.
- Define actions in terms of the events you want to _log_ in the app, instead of thinking about the piece of the state that it's going to change (avoid 1 to 1 relationships between actions and reducers).
- Reduce each part of the state depending on the actions/events (two different parts of the state can be recalculated based on the same action, that's the cool thing).
- In each view, subscribe only to the part of the state that it really needs, even combining different substates. I usually declare the substate for each view (`struct MySubstate { ... }`), make it `Equatable`, and then subscribe to the store like this: `store.subscribe(self) { 0$.select(MySubstate.init) }`.

**Comment by ranhsd** [comment]
Hi @danielmartinprieto thanks for your detailed response. This is exactly how I am working currently. I subscribe to sub-states and use Equatable + SkipRepeates. BTW its not always possible to subscribe to specific model or object of your sub-state but of course that it is possible. If I will implement all your recommendations above (which seems to be correct) it means that in order to get all the info that I need I will need to subscribe to multiple objects or sub-state in part of my view controllers. I can do that (by using blocks instead of delegates) but if you have a look on the example in here:  https://github.com/svdo/ReRxSwift you will notice that it's done in much more generic and nice way but in order to do it I need to use RxSwift which currently is not part of my architecture.

**Comment by danielmartinprieto** [comment]
Hi, @ranhsd. I don't understand this:
> BTW its not always possible to subscribe to specific model or object of your sub-state but of course that it is possible.
and neither this:
> I can do that (by using blocks instead of delegates) but if you have a look on the example [...]
so I can't help you a lot there, but regarding [ReRxSwift](https://github.com/svdo/ReRxSwift#usage), you can do exactly the same until point 4 (included) without the need of `RxSwift`, just using the `ReSwift` API. If you post a small code example illustrating the problem you have, I think I will be able to help you better.

**Comment by ranhsd** [comment]
Hi @danielmartinprieto I really appreciate your help but I think that I will try to figure it out on my own. I like the ReRxSwift approach but the problem is that it is dependent on RxSwift which currently not part of my project.

Anyway, I will try to find some solution and will reopen the issue if I will have more questions.

Thanks a lot!
