### ISSUE TITLE
Documentation on AsyncActionCreator

### ISSUE THREAD

**Issue by sohocoke** [ReSwift/ReSwift#371]
What's the best resource to learn about AsyncActionCreator and when to use it? 

It's not mentioned in the excellent Getting Started Guide, and the comment on the typealias:
```
/// AsyncActionCreators allow the developer to wait for the completion of an async action.
```
still leaves me with questions such as:
- how exactly is this different from an ActionCreator? (since an ActionCreator can return nil, and 'wait until the completion of an async operation' until it dispatches actions)
- what are the situations for which it is useful?

**Comment by danielmartinprieto** [comment]
Hi! This is something that has come up several times already (take a look at the issues). I find them misleading as well because they don't represent they same concept as in the original Redux library (in JavaScript), so I don't use them myself. If I want to include side effects in my app, I follow one of these patterns:
- Crete a middleware (preferred)
- Create functions that get the store and possibly other params and dispatch new actions

I hope this helps.

**Comment by sohocoke** [comment]
@danielmartinprieto Thanks for your response! 

Unfortunately my search didn't turn up any issue that explained what makes AsyncActionCreator unique and where I would use them... Could you kindly point me to the ones you were thinking of?

**Comment by danielmartinprieto** [comment]
Sure, you can find them [here](https://github.com/ReSwift/ReSwift/issues?utf8=%E2%9C%93&q=is%3Aissue+AsyncActionCreator).

**Comment by DivineDominion** [comment]
Would be great if you add your learnings to the Getting Started guide in a PR!

**Comment by danielmartinprieto** [comment]
Let me know what you think about [this PR](https://github.com/ReSwift/ReSwift/pull/372) regarding this!
