### ISSUE TITLE
Replacing actions in middleware?

### ISSUE THREAD

**Issue by ciathyza** [ReSwift/ReSwift#410]
Is it OK to intercept an action in a middleware and replace it with a new action of the same type which is then given back to the next middleware and ultimately to ReSwift's processing?

The reason is I need to modify some action's data in the MW but the action is an immutable struct (and preferably should stay like that).

**Comment by ciathyza** [comment]
... I thin k i answered my own question. Since it's a struct I think there won't be any possible issues that might happen if it were a class. Just want to confirm this.

**Comment by DivineDominion** [comment]
Yes, you get to decide what to pass on to `next`: could be the same action that came in, could be a different action, or you cannot continue at all and swallow the action. Instead of passing a different action to `next`, I prefer to `dispatch` a new action and swallow the current one, effectively filtering it out. This triggers the whole ReSwift (middleware) stack again, and not just whatever comes next. I try to not make the order of Middleware important.
