### ISSUE TITLE
iOS13 will not always call viewWillAppear

### ISSUE THREAD

**Issue by langford** [ReSwift/ReSwift#412]
The view controller lifecycle for modal views is changing.

Example code and readmes that default to viewWillAppear should be updated to note that.

Source

PSA: viewWillDisappear, viewDidDisappear, viewWillAppear and viewDidAppear won't get called on a presenting view controller on iOS 13 which uses a new modal presentation that doesn't cover the whole screen. This may be the largest source of new bugs. https://developer.apple.com/videos/play/wwdc2019/224/ 

https://twitter.com/arekholko/status/1137756105050918912/photo/1

From: https://twitter.com/arekholko/status/1137756105050918912

**Comment by DivineDominion** [comment]
Which point in code will be a good one to set up subscriptions then?

**Comment by mjarvis** [comment]
The appearance methods are called as expected -- since the new modal is not full-screen, the _presenting_ view controller never disappears, and thus the appearance functions are not called.

The functions will still be called as appropriate when the presenter itself was first made visible.
With ReSwift, this is a non-issue. If you add subscribers in `viewWillAppear`, things will continue to work as expected. All visible view controllers will continue to get state updates.
