### ISSUE TITLE
CollectionView cell appearing problem on fast repeatedly calling store.dispatch

### ISSUE THREAD

**Issue by Elshad** [ReSwift/ReSwift#428]
### Problem:
There is the `collectionView` and it calls to fetch nex page data when `if indexPath.section == 0 && indexPath.item >= list.count - 5`. When we scroll fast and reach `(count-5)` index, `(count-4)` index and etc. it calls `store.dispatch` for each indexes (of course this happens very fast) and suddenly all cells disappears. It seems collectionView not calls `collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath)` function.

### Solution: 
Calling `dispatch` in main thread helped me.
```
func collectionView(_ collectionView: UICollectionView, willDisplay cell: UICollectionViewCell, forItemAt indexPath: IndexPath) {
   if indexPath.section == 0 && indexPath.item >= self.props.news.list.count - 5 {
      let action = NewsRedux.FetchAction(next: true)
      DispatchQueue.main.async {
         Redux.shared.dispatch(action)
      }
   }
}
```

### Questions:
Is this means that when we call `dispatch` then whole "reducer process" runs in actual scope, but not sends to next main thread cycle (but not put "reducer process" to main thread queue)?

<img width="937" alt="Screen Shot 2019-10-17 at 11 05 59" src="https://user-images.githubusercontent.com/2334731/66985823-adb8a800-f0ce-11e9-89a3-4b8ff5d2f761.png">

**Comment by DivineDominion** [comment]
Why your cells disappear is a weird problem I think you should look more into 🤔

Regarding your question: You're right, when you call `dispatch`, the state is updated and all subscribers are notified synchronously. In other words, the app "waits" at that point during runtime until every subscriber has been notified of the updated state. This might also include your CollectionView in the end.

So we're all on the same page, I also want to point out that `Redux.shared.dispatch(action)` is called on the main thread in both cases (because the delegate method is called by UIKit on the main thread), but your solution executes the block _asynchronously_.
