### ISSUE TITLE
Shouldn't remove subscribers while iterating

### ISSUE THREAD

**Issue by simon-krucinin-applifting** [ReSwift/ReSwift#429]
Removing subscribers while iterating them is generally not a good idea, see here:
https://github.com/ReSwift/ReSwift/blob/5b9ebd49b166205a89d17a466f03897559379665/ReSwift/CoreTypes/Store.swift#L24

This is a less likely situation. But a problem can also happen when unsubscribing in a subscription (i.e. `newState()`).

**Comment by mjarvis** [comment]
Because `Set` in swift is a value type, this is safe behaviour. While not exactly what is occurring, one could think of `forEach` receiving a copy of the Set, and thus the `remove()` is not acting on the same copy as is being iterated.

For a more correct & descriptive reasoning, see https://stackoverflow.com/a/37998032

This also means it is safe to unsubscribe in `newState(...)`.

If `Set` were a reference type (as `NSSet` is in Objective-C) then you would be correct, and mutating while enumerating in this fashion would likely cause a crash.

**Comment by simon-krucinin-applifting** [comment]
Thank you, I stand corrected. I knew about the copy-on-write semantics, but didn't realize it works with iterators too.
