### ISSUE TITLE
Concurrency, custom dispatch queue

### ISSUE THREAD

**Issue by MichaelGuoXY** [ReSwift/ReSwift#443]
## Question
I have multiple `WarmUp` actions dispatched one after another [here](https://github.com/MichaelGuoXY/ReSwiftExample/blob/master/ReSwiftExample/AppDelegate.swift#L17-L19)

The 2nd action is expected to perform based on the state changes by the 1st action, in this case, the 2nd `WarmUp` action should not go inside [this block](https://github.com/MichaelGuoXY/ReSwiftExample/blob/master/ReSwiftExample/ReSwift/ReSwift.swift#L43-L46) because the `appState.needsWarmup` is already updated to `false` by the 1st action

Everything works fine when I directly use the `Store.dispatch`, but things work weirdly after I tried to create my custom serial dispatch queue for actions.

## Expected - Store.dispatch()
Console logs
```
warmup
Warmup-ing ...
doneWarmup
Done warmup ...
warmup
warmup
```

## Unexpected - Serial Dispatch Queue
Console logs
```
warmup
Warmup-ing ...
warmup
Warmup-ing ...
warmup
Warmup-ing ...
doneWarmup
Done warmup ...
doneWarmup
Done warmup ...
doneWarmup
Done warmup ...
```

I've put the expectations also here in the code comment
https://github.com/MichaelGuoXY/ReSwiftExample/blob/master/ReSwiftExample/ReSwift/ReSwift.swift#L85-L111

I'm not sure if it's the right way that I tried, please do advice on how to use a custom serial queue for actions & state changes

## Sample
https://github.com/MichaelGuoXY/ReSwiftExample

Please download and try, no `pod install` required

**Comment by MichaelGuoXY** [comment]
It's easy to understand with Main thread, the 2nd action will be dispatched after the 1st action being dispatched and states being updated. But how can I achieve the same thing with a custom serial queue?

**Comment by dani-mp** [comment]
Why do you need to dispatch three actions in a row instead of just one?

**Comment by MichaelGuoXY** [comment]
> Why do you need to dispatch three actions in a row instead of just one?

There are cases the same action can be dispatched at almost the same time from different places. No need to be like what's in the example, this is just to reproduce the issue more easily.

**Comment by dani-mp** [comment]
I'm not sure if I understand the problem, but in the middleware, you're dispatching an action before having finished processing the previous one (you're calling `next(action)` at the end). You can call next whenever you want, and then dispatch more actions in your middleware. Does that help?

**Comment by mjarvis** [comment]
The issue you're experiencing is being caused by your use of `mainStore.dispatch` inside of middleware.
Middleware has its own `dispatch` function available (as seen in the closure parameters) that you should be using instead, and indeed fixes the problem.

https://github.com/MichaelGuoXY/ReSwiftExample/blob/bdad901e2018ab87f4c6cb4683042e81e6f217f3/ReSwiftExample/ReSwift/ReSwift.swift#L46

Change `mainStore.dispatch(AppAction.doneWarmup)` to `dispatch(AppAction.doneWarmup)`

By dispatching again on mainStore you were adding the `doneWarmup` to the *END* of your queue, which was already stacked with 3x `warmup` actions, and because it was processing those first, it was also dispatching 3x `doneWarmup`.

In fact, you don't have any invalid concurrency issues occurring, which is why the fatal error is not happening. Your code is perfectly safe, just invalid logically for what you want.

using the provided `dispatch` allows the `doneWarmup` to happen immediately during the processing of the first `warmup`, and fixes the bug.

**Comment by MichaelGuoXY** [comment]
> The issue you're experiencing is being caused by your use of `mainStore.dispatch` inside of middleware.
> Middleware has its own `dispatch` function available (as seen in the closure parameters) that you should be using instead, and indeed fixes the problem.
> 
> https://github.com/MichaelGuoXY/ReSwiftExample/blob/bdad901e2018ab87f4c6cb4683042e81e6f217f3/ReSwiftExample/ReSwift/ReSwift.swift#L46
> 
> Change `mainStore.dispatch(AppAction.doneWarmup)` to `dispatch(AppAction.doneWarmup)`
> 
> By dispatching again on mainStore you were adding the `doneWarmup` to the _END_ of your queue, which was already stacked with 3x `warmup` actions, and because it was processing those first, it was also dispatching 3x `doneWarmup`.
> 
> In fact, you don't have any invalid concurrency issues occurring, which is why the fatal error is not happening. Your code is perfectly safe, just invalid logically for what you want.
> 
> using the provided `dispatch` allows the `doneWarmup` to happen immediately during the processing of the first `warmup`, and fixes the bug.

Thanks, got it now. One more question related to this:

Is it recommended that in the `Middleware` we shouldn't dispatch actions on other queue/thread in order to perform the actions in the wanted order or is it depends on the business logic?

**Comment by mjarvis** [comment]
Correct, @MichaelGuoXY. It is important one considers when the action will be processed when dispatching.
