### ISSUE TITLE
Discussion: struct vs enum

### ISSUE THREAD

**Issue by G4BB3R** [ReSwift/ReSwift#58]
The framework is awesome, I like it because it has many similar concepts of the Elm language.
But I want to know, would not it better to use a enum instead of structs, in the Actions ?

**Comment by Ben-G** [comment]
Hey @G4BB3R!

The usage of enums is definitely possible, and in many cases it is a better option than using structs. I have used different approaches over time and haven't found a favorite - as so often it depends a lot on your specific use case.

Currently we're suggesting structs by default, because that allows you to conform to `StandardActionConvertible`, which some time down the road will hopefully provide you with automatic serialization and deserialization of actions.

That's really the main reason we're using structs in the examples right now.

**Comment by russbishop** [comment]
@G4BB3R I am using this in a project and all my actions are in fact enums; works just fine.

**Comment by Aleksion** [comment]
One thing I will look into before we hit v1 is serialization. 

I'll look into Action serialization and State serialization. And I'll make sure to check whether I can figure out a way to do it with enums as well.

Personally I love defining Actions as such:

```swift
/**
 * And implemented as an enum action
 */
enum CountEnumAction: Action {
    case Increment
    case Decrement
    case Set(Int)
}
```

@garnett came up with this in ReduxKit before we merged efforts - and I have been using it ever since. And the good thing about the API's being so close is that the exact same thing is possible in ReSwift

@G4BB3R  - We're currently focusing on example projects and updated documentation - and I'll make sure the enum actions and its pro's and con's make it in there :)

**Comment by Ben-G** [comment]
I don't think any action is required here; so I'll close this issue!
