### ISSUE TITLE
Confusion about AsyncActionCreator and ActionCreator's accesibility

### ISSUE THREAD

**Issue by itchingpixels** [ReSwift/ReSwift#83]
First: huge thanks for this, it's super interesting!

I came across the problem that in the current released version (the one that cocoapods picks up), AsyncActionCreator and ActionCreator are not public typealiases, which was super confusing at first. Would it worth to release a new version soon? I saw this has been fixed since then.

Cheers!

**Comment by itchingpixels** [comment]
okay, maybe I'll take it back, it seems like I still can't reference these outside of the framework.

I'll post details soon.

**Comment by itchingpixels** [comment]
Okay, so I figured out, I have to reference the typealias like this: 
Store<AppState>.AsyncActionCreator 

The reason why I got confused is because this wasn't mentioned anywhere:). to be honest, I expected a typealias to be public not on a protocol but as "free typepalias".

Is there any specific reason why you wouldn't want to use the ones on StoreType simply as "standalones"?

I mean these:

    typealias ActionCreator = (state: State, store: StoreType) -> Action?

    /// AsyncActionCreators allow the developer to wait for the completion of an async action.
    typealias AsyncActionCreator = (state: State, store: StoreType,
    actionCreatorCallback: ActionCreator -> Void) -> Void

My confusion was elevated by the fact when I redefined both of these in my project, I got a compiler segfault.

**Comment by itchingpixels** [comment]
I guess it's useful to specific the Store generic in the signature to avoid casting and that's why its implemented this way. I'm happy to translate some of the async flow documentation to ReSwift from the original redux docs to make this clear. Where would be a good place to contribute it?

**Comment by Ben-G** [comment]
Hey @itchingpixels! You figured everything out before I could respond - awesome :smiley: 

An update to the docs would be very much appreciated! :+1:  I think it would be best to add a new markdown document to this folder: `/ReSwift/Readme/Async Actions` (or something similar).

Once the PR is merged we will regenerated the docs hosted at http://reswift.github.io/ReSwift to include that chapter.

You also brought up a good point of making a new release. There have been a lot of changes since the last one. I'll take care of that!

Thanks a lot for the contribution :tada:

**Comment by nikans** [comment]
Either I haven't read the docs thoroughly, or it's still not clear how to properly make an ActionCreator. 

This is not clear at all

```
func deleteNote(noteID: Int) -> ActionCreator {
   return { state, store in
       // only delete note if editing is enabled
       if (state.editingEnabled == true) {
           return NoteDataAction.DeleteNote(noteID)
       } else {
           return nil
       }
   }
}
```

What's `NoteDataAction.DeleteNote(noteID)`?

Something like this also doesn't work:

```
let loadMainSequence: Store.ActionCreator = { (_ state: AppState, _ store: Store<AppState>) -> Action? in
    return %someAction%
}
```

I can't `store.dispatch(...)` it, because `Cannot convert value of type 'Store<AppState>' to expected argument type 'Store<State>'` (WAT)

**Comment by nikans** [comment]
Well, I figured it out, I think. For example:

```
func loadMainSequence() -> Store<AppState>.ActionCreator {
    return { state, store in
        ...
        return SetRouteAction([AppRoute.login.string])
    }
}
```

```
store.dispatch(AppRouter().loadMainSequence())
```

This is kinda not obvious from the docs.
